### ISSUE TITLE
401 error to testnet financial server

### ISSUE THREAD

**Issue by AugmentBLU** [coti-io/coti-fullnode#2]
Hi folks, I’ve been running a Testnet node since November 2019 and just stumbled upon an error when carrying out some test transactions. I haven’t seen this before so I’m not sure if it’s something that’s appeared due to a persistent socket issue, something that’s manifested after X amount of time or a new layer of security enabled on your side. 

When sending test transactions, I noticed that the activity feed was showing the status as “attached to DAG” and wouldn’t update even after several minutes. I checked the COTI explorer and could see the transactions set as confirmed. This prompted me to check the dev console and could see a 401 to the Testnet financial server domain. I am assuming this is causing the balanced and statuses to not update - I might be wrong but from here on, it's assuming this is the issue.

I checked other Testnet nodes and they were fine so it was directly related to my node. I made 2 changes at once to test, first I routed the DNS direct to the server instead of using CloudFlare (which routes all my other subdomains) and second, I restarted the service on my server. I logged back in to my Testnet, restored the addresses and could see the balances are now reflecting the right amounts. I ran another couple test transactions and everything now updates as expected, there’s also no 401 error.

I do suspect that it might be that CloudFlare does not expose real IPs to and from servers, would this cause the 401 as the expected IP is not matching that of my server? Or was it that the COTI node service had somehow become corrupt or not fully responsive? It’s been running for over 60 days and I haven’t noticed this issue before. Any ideas, perhaps there's a log on your side to see if there was some sort of blacklist against an IP mismatch? 

**UPDATE** 
I just rechecked and I'm getting the 401 again, transactions are completing though. Bit strange. I logged in to another couple testnet nodes and they're now showing the 401 error. Some others on Telegram have been reporting that nodes haven't been generating addresses and updating balances so seems to be a wider issue that what I've outlined above. 

![image](https://user-images.githubusercontent.com/442602/73221565-1fd26b80-4159-11ea-8db9-c203c75adabf.png)

**Comment by alexstolrcoti** [comment]
Hi @AugmentBLU. this error is returned because your disputes are empty (take a look in financial server at DisputeController:getDisputes endpoint --> DisputeService:getDisputes ).  We will later change the response to be more clear.

Also, please open future issues in coti-node repository.
